version: "3.2"

services:
  request-node:
    image: requestnetwork/request-node:latest
    container_name: request-node
    ports:
      - 3200:3200
    # override the default command
    # wait for request-contracts to terminate before starting the node
    # Without this, the node crashes as it starts before contracts are deployed
    command: sh -c "while ping -c1 request-contracts &>/dev/null; do echo \"wait for request-contracts\";sleep 1; done; echo \"Contracts ready\" && node /node/node_modules/@requestnetwork/request-node/dist/server.js"
    environment:
      # DEBUG: "express:*"
      IPFS_HOST: ipfs
      IPFS_PORT: 5001
      IPFS_TIMEOUT: 5000
      ETHEREUM_NETWORK_ID: 0
      WEB3_PROVIDER_URL: http://ganache:8545
      MNEMONIC: "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat"
      PORT: 3200
    depends_on:
      - ipfs
      - ganache
      - request-contracts

  ipfs:
    image: requestnetwork/request-ipfs:0.4.23-2
    container_name: ipfs
    ports:
      - 5001:5001

  ganache:
    image: trufflesuite/ganache-cli
    container_name: ganache
    ports:
      - 8545:8545
    command:
      - "-m"
      - "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat"

  request-contracts:
    image: requestnetwork/request-contracts:latest
    container_name: request-contracts
    environment:
      WEB3_URL: http://ganache:8545
    depends_on:
      - ganache
